FROM python:latest

RUN mkdir /app && useradd -Md /app app && chown app: /app

USER app
WORKDIR /app
ENV PYTHONPATH=/app

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir install smbmap -t .

CMD ["-h"]
ENTRYPOINT ["/usr/local/bin/python3","-W","ignore","/app/smbmap/smbmap.py"]
