FROM python:3.7-alpine

RUN apk add --update --no-cache git openssl-dev musl-dev curl-dev gcc

ENV PYCURL_SSL_LIBRARY=openssl
RUN pip install wfuzz
RUN git clone --depth 1 https://github.com/xmendez/wfuzz.git

RUN apk del openssl-dev musl-dev gcc
COPY wfuzz.ini /root/wfuzz.ini
WORKDIR /wfuzz

ENTRYPOINT ["/usr/local/bin/wfuzz"]
