services:
  myapp:
    image: debian:buster-slim
    container_name: test_secrets
    secrets:
      - app_secret
    command: ["bash"]
    tty: true

secrets:
  app_secret:
    file: ./app_pass.txt

